//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html



using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Data.Entity.Validation;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;



namespace _2x2_SimpleCRM.DataLayerSQLite
{
    public class SqliteDbContext : DbContext
    {


        public SqliteDbContext() : base("MySqlDbContext")
        {
           
        }

        public DbSet<Client> Clients { get; set; }
        public DbSet<Issue> Issues { get; set; }
    }
  
}
